# Generated by Django 5.2.5 on 2025-11-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
