# Generated by Django 5.2.6 on 2025-12-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='publicaciones/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fuente', models.CharField(choices=[('Blog', 'Blog'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram')], default='Blog', max_length=20)),
                ('url_original', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.DeleteModel(
            name='ArticuloBlog',
        ),
    ]
