# Generated by Django 5.2.6 on 2025-12-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_publicacion_delete_articuloblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
